# Generated by Django 2.2.16 on 2022-05-20 16:05

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=7, validators=[api.validators.HexCodeValidator])),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
