# Generated by Django 2.2.16 on 2022-07-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220717_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'verbose_name': 'IngredientAmount', 'verbose_name_plural': 'IngredientAmounts'},
        ),
    ]
