# Generated by Django 2.2.16 on 2022-07-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220712_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='id',
            new_name='primary_key',
        ),
    ]
