# Generated by Django 2.2.16 on 2022-07-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220719_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Shopping cart', 'verbose_name_plural': 'Shopping carts'},
        ),
    ]
